blueprint:
  name: Lumière Sensorisée
  description: >
    # 💡 Lumière Sensorisée

    **Version : 7.3**


    Votre expérience d'éclairage, à votre façon - prenez le contrôle et personnalisez-la à la perfection ! 💡✨


    **Si vous aimez mes blueprints, et que vous souhaitez montrer votre soutien ou simplement dire merci ?** [Cliquez ici](https://www.paypal.com/donate/?hosted_button_id=WAZS3QSDTPGA8) 🙂


    <details>
    <summary><b>Le Processus d'Automatisation :</b> 👈</summary>


      - **Déclencheur :**
        - Vous pouvez choisir n'importe quel [capteur binaire](https://www.home-assistant.io/integrations/binary_sensor/) ou [horaires](https://www.home-assistant.io/integrations/schedule) pour déclencher l'automatisation.
        - Un capteur de déclenchement, comme un capteur de mouvement, activera les lumières, les interrupteurs, les scènes et les scripts lorsque l'automatisation est déclenchée.
        - Un délai de temps commence le processus d'extinction après que tous les déclencheurs soient clairs. Voir [groupement](https://community.home-assistant.io/t/481048/34) des capteurs pour plus d'informations.
        - Si les déclencheurs sont réactivés avant la fin du délai de temps, l'automatisation se réinitialise pour un éclairage continu.

      - **Intégration de Scène et Script :**
        - Les scènes ou scripts offrent une personnalisation supplémentaire pour vos espaces.

      - **Options de Contrôle de la Lumière :**
          - Utilisez "Contrôle de la Lumière" pour ajuster la luminosité, la température de couleur, la couleur et les temps de transition.

      - **Options d'Éclairage Dynamique :**
        - Optez pour 'Éclairage Dynamique' pour ajuster continuellement la luminosité en fonction des valeurs de lux ou adapter la température de couleur et la luminosité selon l'élévation changeante du soleil.

      - **Override Manuel :**
        - Utilisez les "Options de Contournement" pour un contournement manuel des capteurs de déclenchement, offrant un contrôle manuel et une personnalisation supplémentaire.

      - **Options d'Élévation du Soleil :**
        - Implémentez "Élévation du Soleil" pour restreindre l'automatisation aux conditions plus sombres alignées avec la position du soleil.

      - **Options de Détection de Lumière Ambiante :**
        - Configurez un Capteur de Lumière Ambiante pour l'activation dans des conditions de faible luminosité, personnalisable avec des valeurs LUX spécifiées.

      - **Options Basées sur le Temps :**
        - Spécifiez des heures de début et de fin précises ainsi que des sélections de jours de la semaine pour définir quand l'automatisation doit fonctionner.

      - **Options de Suivi de Dispositif :**
        - Utilisez "Suivi de Dispositif" pour activer l'automatisation quand à la maison ou dans des zones spécifiées, empêchant des activations inutiles. Cette fonctionnalité est particulièrement utile pour prévenir des activations d'éclairage inutiles lorsque des animaux domestiques déclenchent des capteurs alors que personne n'est à la maison.

      - **Mode Lumière de Nuit :**
        - Activez "Lumières de Nuit" pour un éclairage plus doux pendant les activités nocturnes, automatiquement activé selon les conditions.
        - Optez pour utiliser "Night Glow". Cette fonction active une lumière de faible intensité quand aucun déclencheur n'est détecté, créant une lueur ambiante subtile parfaite pour une utilisation nocturne.

      - **Safeguards pour le Redémarrage de Home Assistant :**
        - Bénéficiez de sauvegardes intégrées pour les redémarrages de Home Assistant.

      - **Intégration de l'Add-On du Blueprint :**
        - Lumière Sensorisée Add-On - Améliore l'automatisation du contrôle média. [Cliquez ici](https://community.home-assistant.io/t/591824) pour en savoir plus.
        - Ventilateur d'Épuisement d'Humidité de Salle de Bain - Garde les lumières ALLUMÉES pendant la douche. [Cliquez ici](https://community.home-assistant.io/t/509992) pour en savoir plus.
    </details>


    Besoin d'aide ?

    - Les Paramètres & Lignes Directrices de Meilleures Pratiques : [Cliquez ici](https://community.home-assistant.io/t/481048/345)

    - FAQ : [Cliquez ici](https://community.home-assistant.io/t/481048/6)

    - Support Communautaire y compris les Mises à Jour : [Cliquez ici](https://community.home-assistant.io/t/481048)


    Requis = *
  domain: automation
  input:
    trigger:
      name: "Déclencheur *"
      icon: mdi:cog-outline
      collapsed: true
      input:
        motion_trigger:
          name: Déclencheur Sensor - Capteurs Binaires - Horaire *
          description: >
            Les capteurs de déclenchement sont responsables de l'allumage et de l'extinction des lumières, interrupteurs, scènes et scripts. Vous pouvez choisir n'importe quel [capteur binaire](https://www.home-assistant.io/integrations/binary_sensor/) que vous préférez comme déclencheurs.
            Alternativement, si vous préférez un déclencheur basé sur le temps, vous pouvez également ajouter un [helper de planification](https://community.home-assistant.io/t/481048/1616).
            
            
            Lorsque plusieurs capteurs de déclenchement sont utilisés, il est conseillé de les grouper ensemble en utilisant un helper de groupe.
            Cela assure une exécution plus fluide de l'automatisation et évite les conflits.
            
            
            Pour plus d'informations sur le groupement de vos capteurs de déclenchement [Cliquez ici](https://community.home-assistant.io/t/481048/34)
          default: []
          selector:
            entity:
              filter:
                domain:
                  - binary_sensor
                  - schedule
              multiple: true
    lights_settings:
      name: "Lumières *"
      icon: mdi:lightbulb-outline
      collapsed: true
      input:
        light_switch:
          name: Lumières - Interrupteurs - Scènes - Scripts *
          description: >
            Les lumières, interrupteurs, scènes et scripts qui seront activés par le(s) capteur(s) de déclenchement.
            Si vous ajoutez une scène ou un script, veuillez vous référer à la section 'Scènes & Scripts - Helper de Toggle' et à la section 'Scènes - Scripts à Éteindre' ci-dessous.


            Pour plus d'informations sur l'utilisation des scènes & scripts [Cliquez ici](https://community.home-assistant.io/t/481048/1595)


            **NOTE** - Vous pouvez uniquement utiliser des entités. Les zones, les dispositifs et les étiquettes ne sont pas pris en charge.
          default: []
          selector:
            target:
              entity:
                domain:
                  - light
                  - switch
                  - scene
                  - script
        boolean_scenes_scripts:
          name: Scènes & Scripts - Helper de Toggle
          description: >
            Pour assurer le bon fonctionnement de l'automatisation, il est recommandé de créer un helper de toggle indépendant
            lorsque vous sélectionnez une scène ou un script dans "Lumières - Interrupteurs - Scènes - Scripts" ci-dessus et ensuite l'entrer ici.
          default: []
          selector:
            entity:
              filter:
                domain:
                  - input_boolean
        end_scenes:
          name: Scènes - Scripts à Éteindre
          description: >
            Si vous avez sélectionné une scène ou un script pour être allumé ci-dessus dans "Lumières - Interrupteurs - Scènes - Scripts"
            ou ci-dessous dans "Lumières de Nuit," et que vous souhaitez qu'elle soit éteinte après le délai de temps, alors vous devez créer une scène
            ou un script avec tout éteint et l'entrer ici.
          default: []
          selector:
            entity:
              multiple: true
              filter:
                domain:
                  - scene
                  - script
        time_delay:
          name: Délai de Temps
          description: >
            Le délai de temps détermine combien de temps les lumières, interrupteurs, scènes et scripts resteront actifs après que tous les déclencheurs soient clairs, initiant le délai de temps pour les éteindre.
          default: 5
          selector:
            number:
              min: 0
              max: 30
              step: 0.5
              unit_of_measurement: minutes
    normal_lights_settings:
      name: "Contrôle de la Lumière"
      icon: mdi:lightbulb-on-outline
      collapsed: true
      input:
        include_light_control:
          name: Options de Contrôle de la Lumière (Optionnel)
          description: >
            Sélectionnez si vous souhaitez utiliser la luminosité ou la transition.
            Ces paramètres affecteront uniquement une entité 'lumière' qui supporte chaque option sélectionnée.
            Les paramètres pour la luminosité et la transition sont fournis ci-dessous.
          default: []
          selector:
            select:
              multiple: true
              options:
                - label: Utiliser la Luminosité
                  value: "use_brightness"
                - label: Utiliser la Transition
                  value: "use_transition"
        light_brightness:
          name: Luminosité
          description: >
            Le réglage de luminosité pour les lumières lorsqu'elles sont allumées.
          default: 100
          selector:
            number:
              min: 1
              max: 100
              mode: slider
              step: 1
              unit_of_measurement: '%'
        light_transition_on:
          name: Transition - ON
          description: >
            Le réglage de transition pour les lumières lorsqu'elles sont allumées.
          default: 1
          selector:
            number:
              min: 0
              max: 5
              mode: slider
              step: 0.5
              unit_of_measurement: seconds
        light_transition_off:
          name: Transition - OFF
          description: >
            Le réglage de transition pour les lumières lorsqu'elles sont éteintes.
          default: 1
          selector:
            number:
              min: 0
              max: 30
              mode: slider
              step: 1
              unit_of_measurement: seconds
        include_light_colour_control:
          name: Options de Contrôle de la Couleur de la Lumière (Optionnel)
          description: >
            Sélectionnez si vous souhaitez utiliser la température de couleur, RGB, RGBW ou RGBWW couleur.
            Ces paramètres affecteront uniquement une entité 'lumière' qui supporte chaque option sélectionnée.
            Les paramètres pour la température de couleur, RGB, RGBW et RGBWW couleur sont fournis ci-dessous.
          default: disable_colour_control
          selector:
            select:
              options:
                - label: Utiliser la Température de Couleur
                  value: "use_colour_temperature"
                - label: Utiliser la Couleur RGB
                  value: "use_rgb_colour"
                - label: Utiliser la Couleur RGBW
                  value: "use_rgbw_colour"
                - label: Utiliser la Couleur RGBWW
                  value: "use_rgbww_colour"
                - label: Désactiver le Contrôle de la Couleur
                  value: "disable_colour_control"
        light_colour_temperature:
          name: Température de Couleur
          description: >
            Le réglage de la température de couleur pour les lumières lorsqu'elles sont allumées.
          default: 5000
          selector:
            number:
              min: 2000
              max: 8000
              mode: slider
              step: 100
              unit_of_measurement: 'kelvin'
        light_rgb_colour:
          name: Couleur RGB
          description: >
            Le réglage de la couleur RGB pour les lumières lorsqu'elles sont allumées.
          default: [255, 255, 255]
          selector:
            color_rgb:
        light_rgbw_colour:
          name: Couleur RGBW
          description: >
            Le réglage de la couleur RGBW pour les lumières lorsqu'elles sont allumées.
            Entrez quatre entiers entre 0 et 255 pour définir les valeurs pour Rouge, Vert, Bleu, et Blanc.
          default: [255, 255, 255, 255]
          selector:
            object:
        light_rgbww_colour:
          name: Couleur RGBWW
          description: >
            Le réglage de la couleur RGBWW pour les lumières lorsqu'elles sont allumées.
            Entrez cinq entiers entre 0 et 255 pour définir les valeurs pour Rouge, Vert, Bleu, Blanc Froid et Blanc Chaud.
          default: [255, 255, 255, 255, 255]
          selector:
            object:
